import java.io.IOException;
import okhttp3.Call;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) throws IOException {
        OkHttpClient client = new OkHttpClient.Builder().build();
        Call call = client.newCall(new Request.Builder()
            .url("http://api.stackexchange.com/2.2/questions?order=desc&sort=activity&site=stackoverflow")
            .build());
        Response response = call.execute();
        System.out.println(response.body().string());
    }
}
